import { Inter } from "next/font/google";
import '@/styles/globals.css';
import Nav from "@/components/Nav";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Nav />
                <main className="w-full min-h-screen mt-16 bg-gray-200">
                    {children}
                </main>
            </body>
        </html>
    );
}
