'use client';
import { Inter } from "next/font/google";
import '@/styles/globals.css';
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { useEffect } from "react";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

    useEffect(() => {
        const token = localStorage.getItem('token');

        if(window.location.pathname === '/login' || window.location.pathname === '/register')
            return;


        if(!token)
            window.location.href = '/login';

    } ,[]);
    return (
        <html lang="en">
            <body className={inter.className}>
                <Nav />
                {children}
                <Footer />
            </body>
        </html>
    );
}
